# run on container environment
sudo: false

language: php

notifications:
    email:
        on_success: change
        on_failure: always

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.3
    - php: 5.2
    - php: hhvm
    # WP nightly:
    - env: WP_VERSION=nightly WP_MULTISITE=0
    - env: WP_VERSION=nightly WP_MULTISITE=1
    # WP latest stable:
    - env: WP_VERSION=latest WP_MULTISITE=0
    - env: WP_VERSION=latest WP_MULTISITE=1
    # WP previous stable:
    - env: WP_VERSION=4.5 WP_MULTISITE=0
    - env: WP_VERSION=4.5 WP_MULTISITE=1
  allow_failures:
    # allow failures on WP nightlies:
    - env: WP_VERSION=nightly WP_MULTISITE=0
    - env: WP_VERSION=nightly WP_MULTISITE=1
    # allow failures on PHP beta:
    - php: 7.1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script:
    - if [[ "$WP_VERSION" == "latest" ]]; then if find . -not \( -path ./vendor -prune \) -not \( -path ./features -prune \) -not \( -path ./tests/phpunit/includes/dummy-closures.php -prune \) -name "*.php" -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi; fi;
    - phpunit -v
